In [1]:
import pandas as pd
import sklearn
import numpy as np

Clustering players by shooting ability across our 4 defined shot intervals

Notebook version of player_shots_kmeans.py

In [2]:
#get all players and their fgm & fga at the 5 foot intervals
players_shots = pd.read_csv("./data/player_shots.csv")
players_shots.drop("Unnamed: 0",axis = 1,inplace=True)
players_shots

,player_id,0-4_fgm,0-4_fga,5-9_fgm,5-9_fga,10-14_fgm,10-14_fga,15-19_fgm,15-19_fga,20-24_fgm,20-24_fga,25-29_fgm,25-29_fga,30-34_fgm,30-34_fga,40+_fgm,40+_fga
0,203906,5,14,3,4,1,2,1,2,2,17,2,5,0,0,0,0
1,203894,17,40,1,9,4,9,18,37,25,73,22,59,0,0,0,0
2,201160,355,608,62,174,101,272,472,1016,93,257,5,24,0,0,0,1
3,1626209,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,201228,384,724,70,194,77,187,273,674,386,939,182,485,0,5,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,203901,188,388,59,150,20,60,17,52,12,34,5,23,0,0,0,1
445,203506,483,911,30,111,45,122,107,279,115,330,85,257,0,1,0,2
446,101141,788,1403,85,267,88,263,339,729,281,739,266,721,1,4,0,4
447,202696,827,1348,227,535,144,320,332,759,43,109,3,9,0,2,0,0
448,203095,269,468,35,112,15,49,25,77,108,300,102,254,0,4,1,1

In [3]:
#get each player's fga & fgm at the following intervals
#0-4 feet
rim_shots = players_shots.iloc[:,1:3].values
#5-9 feet
close_shots = players_shots.iloc[:,3:5].values
#10 -1 9 feet
mid_shots = players_shots.iloc[:,5:9].values
#20+ feet
long_shots = players_shots.iloc[:,9:].values

In [4]:
from sklearn.cluster import KMeans
#get cluster for each player for each shot distance cluster
kmeans_short = KMeans(n_clusters = 3,random_state =42).fit(rim_shots)
kmeans_close = KMeans(n_clusters = 3,random_state =42).fit(close_shots)
kmeans_mid = KMeans(n_clusters = 4,random_state =42).fit(mid_shots)
kmeans_long = KMeans(n_clusters = 3,random_state =42).fit(long_shots)

In [5]:
players_shots['short_cluster'] = kmeans_short.labels_
players_shots['close_cluster'] = kmeans_close.labels_
players_shots['mid_cluster'] = kmeans_mid.labels_
players_shots['long_cluster'] = kmeans_long.labels_

In [6]:
ps_clusters = players_shots[['player_id','short_cluster','close_cluster','mid_cluster','long_cluster']]
#save cluster information on its own
ps_clusters.to_csv("./data/player_shot_clusters.csv")

In [7]:
#add player clusters to each shot in database
ps_clusters = pd.read_csv("./data/player_shot_clusters.csv")
all_shots = pd.read_csv("./data/all_shots.csv")
all_shots = all_shots.merge(ps_clusters,left_on='PLAYER_ID',right_on='player_id')
all_shots.to_csv("./data/all_shots_players.csv")